# generated by `direnv hook zsh`
_direnv_hook() {
  trap -- '' SIGINT;
  eval "$("/nix/store/lfl8w8n1anf2d6bwv1wrnvd95prch5v0-direnv-2.31.0/bin/direnv" export zsh)";
  trap - SIGINT;
}
typeset -ag precmd_functions;
if [[ -z "${precmd_functions[(r)_direnv_hook]+1}" ]]; then
  precmd_functions=( _direnv_hook ${precmd_functions[@]} )
fi
typeset -ag chpwd_functions;
if [[ -z "${chpwd_functions[(r)_direnv_hook]+1}" ]]; then
  chpwd_functions=( _direnv_hook ${chpwd_functions[@]} )
fi
